cluster:
  name: dbcluster
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storageSize: 1Gi

bootstrap:
  database: bootstrap
  username: admin
  password: password

users:
  - username: superuser
    password: password
    superuser: true
    createdb: true

#  - username: adokuser
#    password: password
#    superuser: false
#    createdb: true

databases:
  - name: superdb
    user: superuser

#  - name: adokdb
#    user: adokuser
#
#  - name: adoktestdb
#    user: adokuser