cluster:
  name: dbcluster
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storageSize: 1Gi

super:
  database: super
  username: superuser
  password: alpha

users:
  - username: adokuser
    password: adokpw

databases:
  - name: adok
    user: adokuser